In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('/Users/devammpatel/Desktop/Supervised ML Project on Airbnb Dataset/Dataset/Airbnb_Open_Data_Cleaned.csv')
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country code,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,US,...,193.0,10.0,9.0,10/19/2021,0.210000,4.0,6.0,96.0,Clean up and treat the home the way you'd like...,No license
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,US,...,28.0,3.0,45.0,5/21/2022,0.380000,4.0,2.0,96.0,Pet friendly but please confirm with me if the...,No license
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,unconfirmed,Elise,Manhattan,Harlem,40.80902,-73.94190,US,...,124.0,3.0,0.0,9/9/2021,1.376597,5.0,1.0,96.0,"I encourage you to use my kitchen, cooking and...",No license
3,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,US,...,41.0,10.0,9.0,11/19/2018,0.100000,3.0,1.0,96.0,"Please no smoking in the house, porch or on th...",No license
4,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,US,...,115.0,3.0,74.0,6/22/2019,0.590000,3.0,1.0,96.0,"No smoking, please, and no drugs.",No license

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101368 entries, 0 to 101367
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              101368 non-null  int64
 1   NAME                            101368 non-null  str
 2   host id                         101368 non-null  int64
 3   host_identity_verified          101368 non-null  str
 4   host name                       101368 non-null  str
 5   neighbourhood group             101368 non-null  str
 6   neighbourhood                   101368 non-null  str
 7   lat                             101368 non-null  float64
 8   long                            101368 non-null  float64
 9   country code                    101368 non-null  str
 10  instant_bookable                101368 non-null  bool
 11  cancellation_policy             101368 non-null  str
 12  room type                       101368 non-null  str
 13  Construction year               101368 non-null  float64
 14  price                           101368 non-null  float64
 15  service fee                     101368 non-null  float64
 16  minimum nights                  101368 non-null  float64
 17  number of reviews               101368 non-null  float64
 18  last review                     101368 non-null  str
 19  reviews per month               101368 non-null  float64
 20  review rate number              101368 non-null  float64
 21  calculated host listings count  101368 non-null  float64
 22  availability 365                101368 non-null  float64
 23  house_rules                     101368 non-null  str
 24  license                         101368 non-null  str
dtypes: bool(1), float64(11), int64(2), str(11)
memory usage: 43.8 MB

Let's drop unwanted columns

In [4]:
#Dropping the 'id', 'host id', 'NAME', 'host name', 'country code', 'reviews per month', 'house_rules', 'license' columns as they are not useful for our analysis
df.drop(['id', 'host id', 'NAME', 'host name', 'country code', 'reviews per month', 'house_rules', 'license'], axis=1, inplace=True)
df.head()

,host_identity_verified,neighbourhood group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,review rate number,calculated host listings count,availability 365
0,unconfirmed,Brooklyn,Kensington,40.64749,-73.97237,False,strict,Private room,2020.0,966.0,193.0,10.0,9.0,10/19/2021,4.0,6.0,96.0
1,verified,Manhattan,Midtown,40.75362,-73.98377,False,moderate,Entire home/apt,2007.0,142.0,28.0,3.0,45.0,5/21/2022,4.0,2.0,96.0
2,unconfirmed,Manhattan,Harlem,40.80902,-73.94190,True,flexible,Private room,2005.0,620.0,124.0,3.0,0.0,9/9/2021,5.0,1.0,96.0
3,verified,Manhattan,East Harlem,40.79851,-73.94399,False,moderate,Entire home/apt,2009.0,204.0,41.0,10.0,9.0,11/19/2018,3.0,1.0,96.0
4,verified,Manhattan,Murray Hill,40.74767,-73.97500,True,flexible,Entire home/apt,2013.0,577.0,115.0,3.0,74.0,6/22/2019,3.0,1.0,96.0

Now that we are left with only useful data, let's encode the categorical data using onehotencoding technique and numerical data using standardscaler.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101368 entries, 0 to 101367
Data columns (total 17 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   host_identity_verified          101368 non-null  str
 1   neighbourhood group             101368 non-null  str
 2   neighbourhood                   101368 non-null  str
 3   lat                             101368 non-null  float64
 4   long                            101368 non-null  float64
 5   instant_bookable                101368 non-null  bool
 6   cancellation_policy             101368 non-null  str
 7   room type                       101368 non-null  str
 8   Construction year               101368 non-null  float64
 9   price                           101368 non-null  float64
 10  service fee                     101368 non-null  float64
 11  minimum nights                  101368 non-null  float64
 12  number of reviews               101368 non-null  float64
 13  last review                     101368 non-null  str
 14  review rate number              101368 non-null  float64
 15  calculated host listings count  101368 non-null  float64
 16  availability 365                101368 non-null  float64
dtypes: bool(1), float64(10), str(6)
memory usage: 18.2 MB

In [6]:
categorical_cols = ['neighbourhood group', 'neighbourhood', 'room type', 'host_identity_verified', 'cancellation_policy', 'last review']  # list string columns
for col in categorical_cols:
    df[col] = df[col].astype('object')

In [7]:
# Printing the number of numerical and categorical features in the dataset along with their names
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
print(f'Number of numerical features: {len(numerical_cols)}')
print(f'Numerical features: {numerical_cols.tolist()}')
categorical_cols = df.select_dtypes(include=['object']).columns
print(f'Number of categorical features: {len(categorical_cols)}')
print(f'Categorical features: {categorical_cols.tolist()}')

Number of numerical features: 10
Numerical features: ['lat', 'long', 'Construction year', 'price', 'service fee', 'minimum nights', 'number of reviews', 'review rate number', 'calculated host listings count', 'availability 365']
Number of categorical features: 6
Categorical features: ['host_identity_verified', 'neighbourhood group', 'neighbourhood', 'cancellation_policy', 'room type', 'last review']

### Before applying encoding, we will first separate dataset into train and test

In [8]:
from sklearn.model_selection import train_test_split
X = df.drop('price', axis=1)
y = df['price']

In [9]:
X.head()

,host_identity_verified,neighbourhood group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room type,Construction year,service fee,minimum nights,number of reviews,last review,review rate number,calculated host listings count,availability 365
0,unconfirmed,Brooklyn,Kensington,40.64749,-73.97237,False,strict,Private room,2020.0,193.0,10.0,9.0,10/19/2021,4.0,6.0,96.0
1,verified,Manhattan,Midtown,40.75362,-73.98377,False,moderate,Entire home/apt,2007.0,28.0,3.0,45.0,5/21/2022,4.0,2.0,96.0
2,unconfirmed,Manhattan,Harlem,40.80902,-73.94190,True,flexible,Private room,2005.0,124.0,3.0,0.0,9/9/2021,5.0,1.0,96.0
3,verified,Manhattan,East Harlem,40.79851,-73.94399,False,moderate,Entire home/apt,2009.0,41.0,10.0,9.0,11/19/2018,3.0,1.0,96.0
4,verified,Manhattan,Murray Hill,40.74767,-73.97500,True,flexible,Entire home/apt,2013.0,115.0,3.0,74.0,6/22/2019,3.0,1.0,96.0

In [10]:
y

0          966.0
1          142.0
2          620.0
3          204.0
4          577.0
           ...
101363     696.0
101364     909.0
101365     387.0
101366     848.0
101367    1128.0
Name: price, Length: 101368, dtype: float64

In [11]:
#Separating the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((81094, 16), (20274, 16), (81094,), (20274,))

In [13]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 101368 entries, 0 to 101367
Data columns (total 16 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   host_identity_verified          101368 non-null  object
 1   neighbourhood group             101368 non-null  object
 2   neighbourhood                   101368 non-null  object
 3   lat                             101368 non-null  float64
 4   long                            101368 non-null  float64
 5   instant_bookable                101368 non-null  bool
 6   cancellation_policy             101368 non-null  object
 7   room type                       101368 non-null  object
 8   Construction year               101368 non-null  float64
 9   service fee                     101368 non-null  float64
 10  minimum nights                  101368 non-null  float64
 11  number of reviews               101368 non-null  float64
 12  last review                     101368 non-null  object
 13  review rate number              101368 non-null  float64
 14  calculated host listings count  101368 non-null  float64
 15  availability 365                101368 non-null  float64
dtypes: bool(1), float64(9), object(6)
memory usage: 11.7+ MB

In [14]:
# Creating column transformer for encoding categorical features and scaling numerical features
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

numerical_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_features)
    ])

In [15]:
preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 Index(['lat', 'long', 'Construction year', 'service fee', 'minimum nights',
       'number of reviews', 'review rate number',
       'calculated host listings count', 'availability 365'],
      dtype='str')),
                                ('cat',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore'),
                                 Index(['host_identity_verified', 'neighbourhood group', 'neighbourhood',
       'cancellation_policy', 'room type', 'last review'],
      dtype='str'))])

In [16]:
# Applying transformation on training data 
X_train = preprocessor.fit_transform(X_train)

In [17]:
X_train = X_train.toarray()  # Convert sparse matrix to dense array
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,...,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657
0,-0.012430,-0.666344,-1.126198,1.053917,-0.424904,-0.711476,-1.777550,-0.214345,-1.273123,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.537480,-0.410371,-1.126198,0.163474,-0.424904,-0.575155,0.560375,-0.214345,-1.273123,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.363149,0.020752,0.435330,-0.862799,0.052739,-0.484275,-0.998241,-0.121919,-0.687504,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-0.057824,-0.905589,-0.258682,-0.123279,0.052739,-0.666035,0.560375,-0.152728,-1.273123,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.466351,1.286307,0.435330,1.114286,-0.424904,-0.075314,1.339684,-0.214345,-1.254823,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81089,-1.241998,-0.247516,-0.779191,-1.194829,1.485667,-0.257074,-1.777550,-0.214345,0.483736,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
81090,-0.127702,-0.839882,-0.779191,0.797349,-0.424904,0.515408,-0.218933,6.163015,1.691576,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
81091,0.570542,0.625413,0.955840,0.088013,-0.424904,-0.302514,1.339684,-0.214345,0.483736,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
81092,0.722272,-0.214864,-0.779191,1.114286,1.963309,3.514458,-0.218933,-0.214345,0.483736,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
81093,0.199349,-0.978954,0.435330,-0.908076,-0.424904,-0.529715,0.560375,-0.214345,0.483736,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
#Applying transformation on testing data
X_test = preprocessor.transform(X_test)
X_test = X_test.toarray()  # Convert sparse matrix to dense array
pd.DataFrame(X_test)

/Users/devammpatel/Desktop/Supervised ML Project on Airbnb Dataset/venv/lib/python3.14/site-packages/sklearn/preprocessing/_encoders.py:261: UserWarning: Found unknown categories in columns [5] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

,0,1,2,3,4,5,6,7,8,9,...,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657
0,0.559998,0.477069,-0.605688,-0.379847,-0.424904,-0.666035,0.560375,-0.214345,0.264128,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.947991,-0.097560,-1.473204,1.114286,-0.902546,-0.666035,1.339684,-0.214345,2.222294,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.142178,-0.937636,0.955840,0.782257,0.052739,-0.302514,-0.998241,-0.214345,-0.577700,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.298894,-0.716531,-0.432185,0.887903,0.052739,-0.438835,0.560375,-0.214345,-1.273123,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-0.376296,0.818501,-0.085179,-1.285383,1.963309,-0.484275,0.560375,-0.214345,2.167392,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20269,0.454377,-0.449070,0.435330,-0.832615,0.052739,-0.166194,-0.998241,0.124549,0.483736,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20270,-1.089553,-0.856006,-1.126198,-1.707966,-0.424904,0.061007,1.339684,-0.214345,-1.273123,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20271,0.801444,0.629242,-0.258682,0.918087,0.052739,0.833489,-0.218933,-0.183536,0.483736,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20272,-1.830331,0.238631,0.782337,0.118197,-0.902546,0.924370,-0.218933,-0.214345,-0.193387,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20273,-0.398100,-0.007264,0.261827,1.069010,0.052739,2.560215,-1.777550,-0.183536,0.483736,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
#Transformation of y_train and y_test using StandardScaler
scaler = StandardScaler()
y_train = scaler.fit_transform(y_train.values.reshape(-1, 1))
y_test = scaler.transform(y_test.values.reshape(-1, 1))

In [20]:
pd.DataFrame(y_train)

              0
0      1.050192
1      0.162999
2     -0.866025
3     -0.123680
4      1.107528
...         ...
81089 -1.197969
81090  0.799726
81091  0.090575
81092  1.116581
81093 -0.914308

[81094 rows x 1 columns]

In [21]:
pd.DataFrame(y_test)

              0
0     -0.383199
1      1.116581
2      0.778602
3      0.887238
4     -1.279446
...         ...
20269 -0.838866
20270 -1.713989
20271  0.917415
20272  0.123769
20273  1.071316

[20274 rows x 1 columns]

## Applying XGBoostRegressor

In [24]:
#Xgboost Regressor
from xgboost import XGBRegressor
model = XGBRegressor(random_state=42)
model.fit(X_train, y_train.ravel())

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [25]:
#Prediction and evaluation
from sklearn.metrics import mean_squared_error, r2_score
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

Mean Squared Error: 0.005126484932790279
R^2 Score: 0.9948486769865322

### Hyperparameter Tuning

In [26]:
#Hyperparameter tuning using RandomizedSearchCV
from sklearn.model_selection import RandomizedSearchCV
param_dist = {
    'max_depth': [None, 10, 20, 30],
    'learning_rate': [0.01, 0.1, 0.2, 0.3],
    'n_estimators': [100, 200, 300, 400],
    'colsample_bytree': [0.3, 0.5, 0.7, 1],
    'subsample': [0.5, 0.7, 1],
    'gamma': [0, 0.1, 0.2, 0.3]
}

In [27]:
param_dist

{'max_depth': [None, 10, 20, 30],
 'learning_rate': [0.01, 0.1, 0.2, 0.3],
 'n_estimators': [100, 200, 300, 400],
 'colsample_bytree': [0.3, 0.5, 0.7, 1],
 'subsample': [0.5, 0.7, 1],
 'gamma': [0, 0.1, 0.2, 0.3]}

In [28]:
xgb_random = RandomizedSearchCV(estimator=model, param_distributions=param_dist, cv=5, n_iter=10, random_state=42)
xgb_random.fit(X_train, y_train.ravel())

RandomizedSearchCV(cv=5,
                   estimator=XGBRegressor(base_score=None, booster=None,
                                          callbacks=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None, device=None,
                                          early_stopping_rounds=None,
                                          enable_categorical=False,
                                          eval_metric=None, feature_types=None,
                                          feature_weights=None, gamma=None,
                                          grow_policy=None,
                                          importance_type=None,
                                          interaction_constraint...
                                          min_child_weight=None, missing=nan,
                                          monotone_constraints=None,
                                          multi_strategy=None,
                                          n_estimators=None, n_jobs=None,
                                          num_parallel_tree=None, ...),
                   param_distributions={'colsample_bytree': [0.3, 0.5, 0.7, 1],
                                        'gamma': [0, 0.1, 0.2, 0.3],
                                        'learning_rate': [0.01, 0.1, 0.2, 0.3],
                                        'max_depth': [None, 10, 20, 30],
                                        'n_estimators': [100, 200, 300, 400],
                                        'subsample': [0.5, 0.7, 1]},
                   random_state=42)

In [29]:
#Prediction and evaluation
y_pred = xgb_random.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error (RandomizedSearchCV): {mse}')
print(f'R^2 Score (RandomizedSearchCV): {r2}')

Mean Squared Error (RandomizedSearchCV): 0.004526491278453286
R^2 Score (RandomizedSearchCV): 0.9954515776406923

In [30]:
xgb_random.best_params_

{'subsample': 0.5,
 'n_estimators': 400,
 'max_depth': None,
 'learning_rate': 0.1,
 'gamma': 0.3,
 'colsample_bytree': 0.7}

In [32]:
#Model training with best parameters
selectmodel_random = XGBRegressor(**xgb_random.best_params_, random_state=42)
selectmodel_random.fit(X_train, y_train.ravel())

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.7, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=0.3, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=400,
             n_jobs=None, num_parallel_tree=None, ...)

In [33]:
#Predicting the target variable using the best estimator
y_pred = selectmodel_random.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error (Best Estimator): {mse}')
print(f'R^2 Score (Best Estimator): {r2}')

Mean Squared Error (Best Estimator): 0.004526491278453286
R^2 Score (Best Estimator): 0.9954515776406923